# Generated by Django 5.2.5 on 2025-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkdinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email_id',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
