# Generated by Django 5.2.5 on 2025-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkdinapp', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
